"""
EatventureBot V3 - Configuration
Native Resolution Approach: No coordinate scaling in code.
Assets are captured at native resolution by the bot's own vision system.

IMPORTANT: Run 'python tools/setup_zones.py' to configure zones for better accuracy!
"""

from typing import Dict, Tuple, List

# ===== SAFE ZONING CONFIGURATION =====
# Generated by tools/setup_zones.py
# Read more: ZONE_SETUP_GUIDE.md

# Game window region (screen coordinates)
# Format: (x, y, width, height)
GAME_REGION: Tuple[int, int, int, int] = (23, 38, 349, 748)

# Station search area - "The Kitchen Floor" (screen coordinates)
# This is where stations actually exist (excludes top header and bottom menu)
STATION_SEARCH_REGION: Tuple[int, int, int, int] = (35, 171, 315, 510)

# Station search area relative to game region (for cropping screenshots)
# Used by vision system to crop before detection
STATION_SEARCH_REGION_RELATIVE: Tuple[int, int, int, int] = (12, 133, 315, 510)

# Danger zone center - "The Burger/Investor Button" (screen coordinates)
# Bot will avoid clicking within DANGER_RADIUS pixels of this point
DANGER_ZONE_CENTER: Tuple[int, int] = (52, 663)

# Danger zone center relative to game region
DANGER_ZONE_CENTER_RELATIVE: Tuple[int, int] = (29, 625)

# Safety radius around danger zone (pixels)
# Any click within this distance will be REJECTED
DANGER_RADIUS: int = 60  # Don't click within 60px of the Burger button

# Click offsets for station upgrade arrows
# These offsets ensure we hit the station counter, not the arrow directly
# УВЕЛИЧЕНЫ на 20% для лучшего попадания!
STATION_CLICK_OFFSET_X: int = 6   # Offset right from arrow (+20% от 5)
STATION_CLICK_OFFSET_Y: int = 12  # Offset down from arrow (+20% от 10)

# Смещение клика по кнопкам реновации/Fly: центр шаблона может быть выше визуальной кнопки — кликаем ниже
RENOVATE_CLICK_OFFSET_Y: int = 40   # пикселей вниз от центра шаблона, чтобы попасть в кнопку
FLY_CLICK_OFFSET_Y: int = 40       # то же для кнопки перелёта

# ===== DETECTION THRESHOLDS =====
# Template matching confidence levels (0.0 - 1.0)
THRESHOLDS: Dict[str, float] = {
    # Default high confidence
    "default": 0.85,
    
    # Station triggers (снижены: Retina/масштаб дают меньше; логируем точность при ненаходке)
    "upgrade_arrow": 0.78,
    
    # General upgrades menu
    "icon_upgrades": 0.85,
    "blue_button": 0.92,  # УВЕЛИЧЕН! Чтобы находить ТОЛЬКО синие кнопки (не серые!)
    
    # Critical actions - VERY STRICT to avoid ads
    "btn_buy": 0.93,  # Ultra-high threshold to prevent ad clicks
    "unlock_btn": 0.78,  # СНИЖЕН! Unlock button (blue with price) - легче находить
    
    # Confirmations
    "btn_close_x": 0.85,
    "btn_okay": 0.85,
    
    # Level Progression — шаблон с красным знаком (активная кнопка)
    "btn_renovate": 0.70,  # Снижен: Retina/масштаб дают меньше 0.78 при горящей кнопке
    "btn_fly": 0.75,
    "btn_open": 0.70,  # CRITICAL: Lowered from 0.85 to 0.70 for better detection
    "btn_fly_confirm": 0.75,
    "btn_confirm_renovate": 0.75,  # Lowered from 0.85
    
    # Collectibles (снижены для лучшего обнаружения; логируем точность при ненаходке)
    # В логах часто "лучшая точность" 0.66-0.74, поэтому порог делаем ниже.
    "box_floor": 0.68,
    "tip_coin": 0.80,
    
    # Safety - Ad detection (lower threshold to catch variations)
    "btn_ad_close_x": 0.80,
    "ad_close_x_gray": 0.78,
    "btn_ad_play": 0.80,  # We avoid clicking this
}

# ===== TIMING CONFIGURATION =====
TIMERS: Dict[str, float] = {
    # Spatial memory - don't click same station within this window
    "STATION_MEMORY": 20.0,  # seconds
    
    # Action delays
    "CLICK_DELAY": 0.15,  # Small delay after each click
    "MENU_OPEN_WAIT": 0.5,  # Wait for menu to open
    "MENU_CLOSE_WAIT": 0.3,  # Wait for menu to close
    "BUY_LONG_PRESS": 3.0,  # Long press duration for buy button
    "SCROLL_DURATION": 0.4,  # Scroll animation duration
    
    # Loop timing
    "MAIN_LOOP_DELAY": 0.1,  # Main loop iteration delay
    "CAMP_LOOPS": 4,  # Number of loops at bottom (Camp phase)
    "CREEP_DISTANCE": 0.3,  # How far to scroll up (30% of screen)
    # 40s scroll cycle (Quartz)
    "PEEK_INTERVAL": 40.0,  # Seconds between full scroll cycle (top → step down → bottom)
    "SCROLL_TOP_DISTANCE_FAST": 150,  # Pixels per fast drag when flying to top
    "SCROLL_STEP_DOWN_DISTANCE": 120,  # Pixels per smooth step when scanning down
    "SCROLL_SWIPE_UP_AT_BOTTOM": 80,  # Small swipe up when hit bottom
    # Порог и количество шагов для детекции "упёрлись" (чуть повышены, чтобы быстрее понимать, что достигли края)
    "SCROLL_CHANGE_THRESHOLD_PCT": 10.0,  # Screenshot diff % to consider "stuck" (higher = считаем край чуть раньше)
    "SCROLL_STUCK_STEPS_REQUIRED": 2,  # Consecutive low-change steps before declaring bottom/top
    "SCROLL_MAX_STEPS_DOWN": 28,  # Max steps when scrolling down in 40s cycle (long maps need more)
    # Idle: if nothing to do for this many seconds, scroll down once (Quartz)
    "IDLE_SCROLL_SECONDS": 4.0,
    "IDLE_SCROLL_DISTANCE": 80,
    # Перелёт: ожидание анимации после Fly_confirm (дольше, чем реновация)
    "FLY_ANIMATION_WAIT": 5.0,
    "FLY_OPEN_WAIT_AFTER": 2.0,
    # После подтверждения реновации/флай: ждём кнопку OPEN до N секунд, опрос каждые M с
    "RENOVATE_OPEN_WAIT_MAX": 10.0,
    "RENOVATE_OPEN_POLL_INTERVAL": 0.4,
}

# ===== INPUT CONFIGURATION =====
INPUT_CONFIG: Dict[str, any] = {
    # Random jitter for human-like clicks (±pixels)
    "CLICK_JITTER": 3,
    
    # Scroll parameters
    "SCROLL_PIXELS": 400,  # Scroll distance in pixels
    "SCROLL_STEPS": 20,  # Number of steps for smooth scrolling
}

# ===== ASSET PATHS =====
ASSETS_DIR = "assets"
# Папка с картинками «не нажимать» — при старте бот ищет все *.png/*.jpg в ней и запрещает клики по ним
ASSETS_NO_DIR = "assets/No"
# Расширение зоны (пиксели) вокруг каждой найденной картинки из ASSETS_NO_DIR
NO_CLICK_AUTO_EXPAND = 20

# Asset filename mapping
# ТОЛЬКО файлы которые РЕАЛЬНО ЕСТЬ в assets/
ASSETS: Dict[str, str] = {
    # Triggers (Menu Openers)
    "icon_upgrades": "icon_upgrades.png",
    "upgrade_arrow": "upgrade_arrow.png",
    "box_floor": "box_btn.png",  # box_btn.png (не box_floor.png)
    "tip_coin": "tip_coin.png",
    
    # Actions (Clicks)
    "btn_buy": "btn_buy.png",
    "blue_button": "blue_button.png",
    "unlock_btn": "Unlock_btn.png",  # Кнопка разблокировки станции (синяя с ценой)
    
    # Level Progression (Реновация + Перелёт после ~5 уровней)
    "btn_renovate": "rennovate_btn.png",              # Кнопка реновации
    "btn_confirm_renovate": "Rennovare_apply_btn.png", # Кнопка подтверждения (Apply)
    "btn_open": "Open_btn.png",                        # Кнопка открытия нового уровня
    "btn_fly": "Fly_btn.png",                          # Перелёт (после ~5 уровней)
    "btn_fly_confirm": "Fly_confirm.png",              # Подтверждение перелёта
    
    # Confirmations/Closing
    "btn_close_x": "btn_close_x.png",
}

# ===== LOGGING =====
LOG_LEVEL = "INFO"  # DEBUG, INFO, WARNING, ERROR
LOG_FORMAT = "%(asctime)s [%(levelname)s] %(message)s"
LOG_DATE_FORMAT = "%H:%M:%S"
